import { link, icon } from './ui-kit.mjs';

const tile = (name, tone) => `<span class="studio-icon ${tone}">${icon(name)}</span>`;
const lesson = (name, title, detail, tone, status) => `<div class="preview-lesson">${tile(name,tone)}<div><strong>${title}</strong><p>${detail}</p></div><span class="preview-status ${tone}">${status}</span></div>`;
const modes = [['classes','Lớp học','book'],['assignments','Bài tập','file'],['calendar','Lịch học','calendar'],['results','Kết quả','chart']];

export const homeContent = `
<div class="studio-home">
<section class="studio-hero"><div class="container studio-hero-grid">
  <div class="studio-intro">
    <h1>Hỗ trợ giáo viên,<br><span>nâng bước học sinh</span></h1>
    <p class="studio-lead">Hỗ trợ giáo viên và học sinh trên con đường chinh phục Tiếng Anh cùng công nghệ mới nhất từ Google và Microsoft</p>
    <div class="studio-actions">${link('login.html?role=teacher','Tôi là giáo viên','primary')}${link('login.html?role=student','Tôi là học sinh','outline')}</div>
  </div>
  <div class="product-stage">
    <div class="stage-orbit" aria-hidden="true"></div><div class="stage-spark" aria-hidden="true">${icon('plus')}</div>
    <div class="floating-skill"><span class="mini-skill-icons">${tile('book','blue')}${tile('audio','green')}${tile('pen','violet')}${tile('mic','amber')}</span><strong>Bốn kỹ năng, một nơi</strong></div>
    <section class="product-screen" aria-label="Khám phá giao diện mẫu">
      <header class="screen-chrome"><div class="screen-dots" aria-hidden="true"><i></i><i></i><i></i></div><span>englishassistant · Giao diện minh họa</span>${icon('shield')}</header>
      <div class="screen-body">
        <div class="screen-heading"><div><p>KHÔNG GIAN HỌC TẬP</p><h2>Hôm nay, học gì nhỉ?</h2></div><span class="preview-avatar">LA</span></div>
        <div class="preview-summary"><div><strong>02<span>lớp học</span></strong>${icon('book')}</div><div><strong>04<span>bài cần làm</span></strong>${icon('file')}</div><div><strong>03<span>nhận xét mới</span></strong>${icon('check')}</div></div>
        <div class="preview-tabs" role="group" aria-label="Chọn tính năng xem trước">${modes.map(([id,label,i])=>`<button type="button" data-preview="${id}" aria-pressed="${id==='assignments'}" aria-controls="preview-${id}">${icon(i)}${label}</button>`).join('')}</div>
        <div class="preview-panel" id="preview-assignments"><div class="preview-panel-title"><h3>Bài tập của bạn</h3><span>Tuần này</span></div>${lesson('book','Finding the main idea','Reading · IELTS Foundation','blue','Cần làm')}${lesson('pen','A place to remember','Writing · IELTS Intensive','violet','Bản nháp')}<div class="preview-bottom">${icon('clock')} Tiếp tục từ nơi bạn đã dừng lại.</div></div>
        <div class="preview-panel" id="preview-classes" hidden><div class="preview-panel-title"><h3>Lớp học của bạn</h3><span>2 lớp</span></div>${lesson('book','IELTS Foundation','Thứ 2 · 4 · 6, lúc 18:30','blue','Vào lớp')}${lesson('users','IELTS Intensive','Thứ 3 · 5, lúc 20:00','green','Vào lớp')}<div class="preview-bottom">${icon('users')} Bài học và giáo viên luôn ở đây.</div></div>
        <div class="preview-panel" id="preview-calendar" hidden><div class="preview-panel-title"><h3>Lịch học trong tuần</h3><span>Tháng 9</span></div><div class="preview-week">${[['T2','21'],['T3','22'],['T4','23'],['T5','24'],['T6','25']].map(([d,n],i)=>`<span class="${i===2?'today':''}">${d}<b>${n}</b></span>`).join('')}</div>${lesson('calendar','Reading cùng lớp','18:30 – 20:00 · IELTS Foundation','blue','Hôm nay')}<div class="preview-bottom">${icon('clock')} Một lịch chung cho bài học và hạn nộp.</div></div>
        <div class="preview-panel" id="preview-results" hidden><div class="preview-panel-title"><h3>Phản hồi mới nhất</h3><span>Đã công bố</span></div><div class="preview-result"><span class="result-orbit">8<span>/10 câu</span></span><div><strong>Reading · Main ideas</strong><p>Em đã nắm tốt ý chính. Đọc kỹ hơn các chi tiết ở câu 3 và câu 7 nhé!</p></div></div><div class="preview-bottom">${icon('check')} Nhận xét giúp bạn biết nên ôn tập điều gì.</div></div>
      </div>
      <footer class="screen-footer"><span class="preview-indicator"></span> Giao diện minh họa</footer>
    </section>
    <div class="floating-feedback">${tile('check','green')}<div><strong>Có nhận xét mới từ giáo viên</strong><p>“Phần mở bài của em rất tốt!”</p></div><span class="feedback-dot"></span></div>
  </div>
</div></section>
<section class="container studio-skills" aria-label="Bốn kỹ năng tiếng Anh"><div class="skills-heading"><p>CÙNG LUYỆN TẬP</p><h2>Đủ bốn kỹ năng. <br>Đúng nhịp của bạn.</h2></div>${[['book','blue','Reading'],['audio','green','Listening'],['pen','violet','Writing'],['mic','amber','Speaking']].map(([i,c,t])=>`<article class="studio-skill ${c}">${tile(i,c)}<h3>${t}</h3></article>`).join('')}</section>
<section class="container studio-features" id="features"><div class="studio-section-heading"><div><h2>Ít việc vụn vặt hơn.<br><span>Nhiều kết nối hơn.</span></h2></div></div>
<div class="feature-mosaic">
  <article class="mosaic-card mosaic-teacher"><div class="mosaic-copy"><span class="audience-tag">${icon('book')} Dành cho giáo viên</span><h3>Lớp học gọn gàng.<br>Dạy theo cách của thầy cô.</h3><p>Bài tập, hạn nộp và học viên được sắp xếp theo lớp. Dễ dàng theo dõi mà không bỏ sót học sinh nào.</p>${link('login.html?role=teacher','Khám phá không gian giáo viên','text')}</div><div class="teacher-canvas" aria-label="Minh họa lớp học"><div class="canvas-class"><span class="class-monogram">F</span><div><strong>IELTS Foundation</strong><p>Reading & Writing</p></div><span class="canvas-members" aria-hidden="true"><i>LA</i><i>MH</i><i>+8</i></span></div><div class="canvas-assignment">${tile('file','blue')}<div><strong>Bài tập tuần này</strong><p>Finding the main idea</p></div><span class="canvas-check">${icon('check')}</span></div><div class="canvas-progress"><span>Tiến độ nộp bài <b>8 / 10 học sinh</b></span><div><i></i></div></div><span class="canvas-caption">Dữ liệu minh họa</span></div></article>
  <article class="mosaic-card mosaic-student"><div class="student-canvas"><div class="practice-ring"><div>${icon('check')}<strong>Thêm một bài<br>đã hoàn thành!</strong></div></div><span class="practice-chip">${icon('pen')} Writing practice</span><span class="practice-star" aria-hidden="true">${icon('plus')}</span></div><div class="mosaic-copy"><span class="audience-tag">${icon('users')} Dành cho học sinh</span><h3>Mỗi bài làm,<br>một bước tiến của riêng bạn.</h3><p>Không gian học tập khoa học, phản hồi từ giáo viên và phân tích kĩ năng dành riêng cho từng học sinh.</p>${link('login.html?role=student','Mở góc học tập của bạn','text')}</div></article>
  <article class="mosaic-card mosaic-schedule"><div class="mosaic-copy">${tile('calendar','blue')}<h3>Nhớ buổi học.<br>Kịp hạn nộp.</h3><p>Dễ dàng theo dõi lịch học và bài tập, xây dựng một lịch trình khoa học hơn.</p></div><div class="schedule-canvas"><div class="schedule-days"><span>T2<b>21</b></span><span>T3<b>22</b></span><span class="selected">T4<b>23</b></span><span>T5<b>24</b></span></div><div class="schedule-event">${icon('book')}<div><strong>Reading cùng lớp</strong><span>18:30 – 20:00</span></div></div></div></article>
  <article class="mosaic-card mosaic-feedback"><div class="mosaic-copy">${tile('chart','violet')}<h3>Không chỉ là điểm số.</h3><p>Chế độ đánh giá tổng quan giúp học sinh hiểu rõ hơn khả năng và điều cần cải thiện.</p></div><figure class="skill-chart" aria-label="Đánh giá kỹ năng minh họa: Đọc 86 phần trăm, Nghe 74 phần trăm, Viết 69 phần trăm, Nói 80 phần trăm."><svg viewBox="0 0 240 190" aria-hidden="true"><polygon class="chart-grid" points="120,16 218,95 120,174 22,95"/><polygon class="chart-grid chart-grid-inner" points="120,43 184,95 120,147 56,95"/><path class="chart-axis" d="M120 16v158M22 95h196"/><polygon class="chart-area" points="120,27 194,95 120,149 56,95"/><circle cx="120" cy="27" r="5"/><circle cx="194" cy="95" r="5"/><circle cx="120" cy="149" r="5"/><circle cx="56" cy="95" r="5"/></svg><figcaption><span><b>Đọc</b><em>86%</em></span><span><b>Nghe</b><em>74%</em></span><span><b>Viết</b><em>69%</em></span><span><b>Nói</b><em>80%</em></span></figcaption></figure></article>
</div></section>
<section class="studio-journey" id="how-it-works"><div class="container"><div class="studio-section-heading centered"><p class="section-label">BẮT ĐẦU THẬT TỰ NHIÊN</p><h2>Từ “chào lớp” đến <span>“em hiểu rồi”.</span></h2></div><div class="journey-cards">${[['01','users','Vào lớp của bạn','Tham gia vào lớp học cùng giáo viên và các bạn khác.'],['02','pen','Cùng nhau luyện tập','Nhận bài, xem yêu cầu và hoàn thành theo nhịp học của mình.'],['03','chart','Nhìn lại để tiến bộ','Nhận xét để học tập, phân tích kĩ năng và cải thiện tốt hơn.']].map(([n,i,t,p])=>`<article><div class="journey-icon">${icon(i)}<span>${n}</span></div><h3>${t}</h3><p>${p}</p></article>`).join('')}</div></div></section>
<section class="container studio-cta-section"><div class="studio-cta"><div><p>MỘT BUỔI HỌC MỚI ĐANG CHỜ</p><h2>Mở lớp học.<br>Mở thêm những khả năng.</h2><div class="studio-actions">${link('register.html','Tạo tài khoản','white')}${link('login.html','Đã có tài khoản? Đăng nhập','text','')}</div></div><div class="cta-art" aria-hidden="true"><span>${icon('book')}</span><span>${icon('audio')}</span><span>${icon('pen')}</span><span>${icon('mic')}</span><i></i></div></div></section>
</div>`;
