import { homeContent } from './home-content.mjs';
import { icon, link, button, badge, input, area, select, panel, table, stat, empty, skill, demo, pageHead, people, person, bars, calendar, brand } from './ui-kit.mjs';
export const pages=[];
const add=(file,title,content,role='',nav='',layout='public')=>pages.push({file,title,content,role,nav:nav||file,layout});
const saveButton=(text='Lưu thay đổi')=>`<button class="btn primary" type="submit">${icon('check')}${text}</button>`;
const filter=(placeholder='Tìm kiếm...',options=['Tất cả'])=>`<div class="toolbar"><label class="search-field">${icon('search')}<input type="search" data-search placeholder="${placeholder}" aria-label="${placeholder}"></label><label class="sr-only" for="status-filter">Lọc trạng thái</label><select id="status-filter" data-filter>${options.map(o=>`<option>${o}</option>`).join('')}</select></div><p class="filter-empty" hidden>Không có kết quả phù hợp.</p>`;
const searchOnly=(placeholder='Tìm kiếm...')=>`<div class="toolbar"><label class="search-field">${icon('search')}<input type="search" data-search placeholder="${placeholder}" aria-label="${placeholder}"></label></div><p class="filter-empty" hidden>Không có kết quả phù hợp.</p>`;
const teacherClassDirectory=()=>`<section class="teacher-class-hero" aria-labelledby="teacher-classes-title"><div class="teacher-class-hero-copy"><p class="teacher-class-kicker">${icon('book')} KHÔNG GIAN GIẢNG DẠY</p><h1 id="teacher-classes-title">Lớp học của bạn</h1><p>Tổ chức lớp, kết nối học sinh và theo dõi hành trình học tập trong một không gian duy nhất.</p></div><div class="teacher-class-hero-summary" aria-label="Tóm tắt lớp học"><div><span>Lớp đang dạy</span><strong data-count="classes">—</strong><small>Không gian học tập của bạn</small></div><div><span>Học sinh</span><strong data-total-students>—</strong><small>Đang tham gia các lớp</small></div></div>${link('teacher-class-new.html','Tạo lớp mới','white','plus')}</section><section class="teacher-class-directory" aria-labelledby="teacher-class-directory-title"><div class="teacher-class-directory-head"><div><p class="teacher-class-section-label">DANH SÁCH LỚP</p><h2 id="teacher-class-directory-title">Không gian lớp học</h2><p>Mở lớp để giao bài, xem học sinh và quản lý lịch học.</p></div>${searchOnly('Tìm theo tên hoặc mã lớp')}</div><div id="class-list" class="class-grid teacher-class-grid"></div></section>`;
const studentClassDirectory=()=>`<section class="student-class-hero" aria-labelledby="student-classes-title"><div class="student-class-hero-copy"><p class="student-class-kicker">${icon('book')} KHÔNG GIAN HỌC TẬP</p><h1 id="student-classes-title">Lớp của tôi</h1><p>Tập trung bài tập, lịch học và kết quả trong từng không gian bạn tham gia.</p></div><div class="student-class-hero-summary" aria-label="Tóm tắt hành trình học tập"><div><span>Lớp đang tham gia</span><strong data-count="classes">—</strong><small>Không gian học tập của bạn</small></div><div><span>Bài tập chờ làm</span><strong data-count="assignments">—</strong><small>Sẵn sàng để chinh phục</small></div></div><div class="student-class-hero-actions">${button('Tham gia lớp','open-student-join','white','plus')}${button('Làm bài tập','open-student-assignments','white','file')}</div></section><section class="student-class-directory" aria-labelledby="student-class-directory-title"><div class="student-class-directory-head"><div><p class="student-class-section-label">KHÔNG GIAN CỦA BẠN</p><h2 id="student-class-directory-title">Tiếp tục hành trình học tập</h2><p>Chọn một lớp để xem bài tập, lịch học và phản hồi mới nhất.</p></div>${searchOnly('Tìm lớp học')}</div><div id="class-list" class="class-grid student-class-grid"></div></section>`;
const studentRows=(admin=false)=>people.map(([i,n,e,c,s])=>[person(i,n,e),admin?'Học sinh':c,badge(s,s==='Tạm nghỉ'?'amber':'green'),link(admin?'admin.html#user-detail':'teacher-student-detail.html','Xem hồ sơ','text','arrow')]);
const adminUserActions=()=>`<div class="admin-user-actions"><a class="class-student-action edit" href="admin.html#user-detail" aria-label="Chỉnh sửa người dùng" title="Chỉnh sửa người dùng">${icon('pen')}</a><button class="class-student-action delete" type="button" data-action="delete-user" aria-label="Xóa người dùng" title="Xóa người dùng">${icon('trash')}</button></div>`;
const adminUserRows=()=>[...people.map(([i,n,e])=>[person(i,n,e),'Học sinh',adminUserActions()]),[person('GV','Giáo viên mẫu','teacher@example.test'),'Giáo viên',adminUserActions()]];
const classStudentTable=()=>`<div class="table-scroll"><table class="class-students-table"><thead><tr><th scope="col">Học sinh</th><th scope="col">Điểm trung bình</th><th scope="col">Hành động</th></tr></thead><tbody data-class-student-rows></tbody></table></div>`;
const scheduleList=`<div class="schedule-item"><div class="time-block">18:30<small>20:00</small></div><div><span class="badge blue">Reading</span><h3>IELTS Foundation</h3><p>Đọc hiểu & chiến lược tìm ý chính</p></div></div><div class="schedule-item"><div class="time-block">20:15<small>21:15</small></div><div><span class="badge violet">Speaking</span><h3>IELTS Intensive</h3><p>Part 2 · Describe a place</p></div></div>`;
const tabs=(links)=>`<nav class="tabs" aria-label="Điều hướng nội dung">${links.map(([href,text,active])=>`<a href="${href}" class="${active?'active':''}">${text}</a>`).join('')}</nav>`;
const fourSkills=()=>`<div class="skill-grid">${[['Reading','Đọc sâu, hiểu đúng','book'],['Listening','Lắng nghe có chủ đích','audio'],['Writing','Viết rõ, diễn đạt tốt','pen'],['Speaking','Tự tin trong từng câu nói','mic']].map(([n,t,i])=>`<article class="feature-card">${skill(n)}<h3>${n}</h3><p>${t}</p></article>`).join('')}</div>`;

add('index.html','Trang chủ',homeContent);

function authPage(mode,admin=false){
  const titles={login:admin?'Đăng nhập quản trị':'Chào mừng trở lại',register:'Tạo tài khoản',forgot:'Quên mật khẩu?',reset:'Tạo mật khẩu mới'};
  let fields='';
  if(mode==='login'||mode==='register'){
    fields=(!admin?`<fieldset class="role-picker"><legend>Bạn tham gia với vai trò</legend><label><input type="radio" name="role" value="teacher" checked><span>${icon('book')}Giáo viên</span></label><label><input type="radio" name="role" value="student"><span>${icon('users')}Học sinh</span></label></fieldset>`:'<p class="admin-label">'+icon('shield')+' Khu vực dành riêng cho quản trị viên</p>')+
    (mode==='register'?input('Họ và tên','name','text','Nhập họ và tên','required maxlength="100" autocomplete="name"'):'')+
    input('Email','email','email',admin?'admin@example.test':'ban@example.test','required autocomplete="username"')+
    `<label class="field">Mật khẩu<span class="password-wrap"><input id="password" name="password" type="password" placeholder="Nhập mật khẩu" required ${mode==='register'?'minlength="8"':''} autocomplete="${mode==='register'?'new-password':'current-password'}"><button type="button" class="icon-btn" data-action="password" aria-label="Hiện mật khẩu">${icon('eye')}</button></span></label>`+
    (mode==='register'?input('Xác nhận mật khẩu','confirm','password','Nhập lại mật khẩu','required minlength="8" autocomplete="new-password"'):`<div class="form-inline"><label class="check-field"><input type="checkbox" name="remember">Ghi nhớ đăng nhập</label><a href="forgot-password.html${admin?'?admin=1':''}">Quên mật khẩu?</a></div>`)+
    (mode==='register'?`<label class="check-field"><input type="checkbox" required>Tôi đồng ý với Thông tin và điều khoản sử dụng</label>`:'');
  }else if(mode==='forgot') fields=input('Email tài khoản','email','email','ban@example.test','required autocomplete="email"');
  else fields=input('Mật khẩu mới','password','password','Ít nhất 8 ký tự','required minlength="8" autocomplete="new-password"')+input('Xác nhận mật khẩu','confirm','password','Nhập lại mật khẩu','required minlength="8" autocomplete="new-password"');
  const label={login:'Đăng nhập',register:'Tạo tài khoản',forgot:'Gửi liên kết khôi phục',reset:'Đặt lại mật khẩu'}[mode];
  return `<main class="auth-layout"><aside class="auth-story ${admin?'admin-story':''}">${brand}<div class="auth-story-content"><span class="auth-kicker">${admin?'ENGLISH ASSISTANT ADMIN':'DẠY VÀ HỌC TIẾNG ANH'}</span><h2>${admin?'Vận hành rõ ràng.<br>Quản lý chủ động.':'Bài học hôm nay.<br>Nhận xét cho ngày mai.'}</h2><p>${admin?'Không gian riêng để quản lý người dùng, lớp học và cấu hình hệ thống.':'Xem bài tập, theo dõi lớp học và trao đổi qua từng nhận xét của giáo viên.'}</p><div class="auth-class-notes"><p><span>01</span> Lớp học và lịch học</p><p><span>02</span> Bài tập theo từng kỹ năng</p><p><span>03</span> Kết quả và nhận xét</p></div></div><small>English Assistant · Learn. Practice. Grow.</small></aside><section class="auth-form-side"><div class="auth-form-container">${admin?'<span class="tagline">QUẢN TRỊ HỆ THỐNG</span>':''}<h1>${titles[mode]}</h1><p class="auth-description">${mode==='login'?'Chọn vai trò và đăng nhập để tiếp tục.':mode==='register'?'Tạo không gian riêng cho việc dạy và học tiếng Anh.':mode==='forgot'?'Nhập email để xem trước quy trình khôi phục tài khoản.':'Chọn một mật khẩu mới cho tài khoản của bạn.'}</p><form data-form="${admin?'admin-login':mode}">${fields}<p class="form-error" role="alert" hidden></p><button class="btn primary full-width" type="submit">${label}${icon('arrow')}</button></form><p class="auth-switch">${mode==='login'?(admin?`<a href="login.html">← Đăng nhập giáo viên / học sinh</a>`:`Chưa có tài khoản? <a href="register.html">Đăng ký ngay</a>`):mode==='register'?`Đã có tài khoản? <a href="login.html">Đăng nhập</a>`:`<a href="${admin?'admin-login':'login'}.html">← Quay lại đăng nhập</a>`}</p></div></section></main>`;
}
add('login.html','Đăng nhập',authPage('login'),'','','auth');
add('register.html','Đăng ký',authPage('register'),'','','auth');
add('forgot-password.html','Khôi phục mật khẩu',authPage('forgot'),'','','auth');
add('reset-password.html','Đặt lại mật khẩu',authPage('reset'),'','','auth');
add('admin-login.html','Đăng nhập quản trị',authPage('login',true),'','','auth');

function taskList(id='assignment-list', cls=''){return `<div id="${id}" class="task-list ${cls}"><p class="loading">Đang tải bài tập mẫu…</p></div>`;}
const teacherClassControls=()=>`<div class="class-carousel-controls"><button class="icon-btn class-carousel-control" type="button" data-action="class-prev" aria-label="Xem lớp trước">←</button><button class="icon-btn class-carousel-control" type="button" data-action="class-next" aria-label="Xem lớp tiếp theo">→</button></div>`;
const teacherClassCarousel=()=>`<div class="class-carousel" aria-label="Lớp học của bạn"><div id="class-summary" class="class-grid compact class-carousel-track" tabindex="0"></div><p id="class-carousel-status" class="sr-only" aria-live="polite"></p></div>`;
const teacherDashboard=()=>`<section class="teacher-dashboard-hero" aria-labelledby="teacher-dashboard-title"><div><p class="teacher-dashboard-kicker">${icon('grid')} BẢNG ĐIỀU KHIỂN GIẢNG DẠY</p><h1 id="teacher-dashboard-title">Tổng quan</h1><p class="teacher-dashboard-greeting">Xin chào <span data-teacher-name>Giáo viên mẫu</span>, thầy/cô sẽ làm gì hôm nay?</p><div class="teacher-dashboard-hero-actions">${link('teacher-classes.html','Xem lớp học','white','book')}${link('teacher-submissions.html','Bài chờ nhận xét','ghost','file')}</div></div><aside class="teacher-dashboard-next-session"><span class="teacher-dashboard-session-icon">${icon('calendar')}</span><div><p>BUỔI HỌC TIẾP THEO</p><strong>18:30 · Reading</strong><span>IELTS Foundation</span></div><a href="teacher-class-detail.html?tab=schedule" aria-label="Xem lịch trình lớp IELTS Foundation">${icon('arrow')}</a></aside></section><div class="teacher-dashboard-stats">${stat('Lớp đang dạy','—','Không gian học tập đang vận hành','book','blue','data-count="classes"')}${stat('Bài đã nộp','—','Bài làm cần theo dõi','file','violet','data-count="submissions"')}${stat('Bài đã giao','—','Bài tập đã gửi đến lớp','file','green','data-count="assignments"')}</div><div class="teacher-dashboard-grid"><section class="teacher-dashboard-classes">${panel('Lớp học đang dạy',teacherClassCarousel(),teacherClassControls(),'teacher-dashboard-class-panel')}</section><aside class="teacher-dashboard-side"><section class="teacher-review-spotlight"><span class="teacher-review-spotlight-icon">${icon('file')}</span><p>BÀI TẬP CẦN XỬ LÝ</p><strong data-count="review">—</strong><h2>bài tập đang chờ nhận xét</h2><span>Kiểm tra bài làm và công bố phản hồi cho học sinh khi sẵn sàng.</span>${link('teacher-submissions.html','Mở danh sách','white','arrow')}</section>${panel('Lịch trình hôm nay',scheduleList,link('teacher-class-detail.html?tab=schedule','Xem lịch','text','calendar'),'teacher-schedule-panel')}</aside></div>`;
const studentDashboard=()=>`<section class="student-dashboard-hero" aria-labelledby="student-dashboard-title"><div class="student-dashboard-copy"><p class="student-dashboard-kicker">${icon('book')} HÀNH TRÌNH HỌC TẬP</p><h1 id="student-dashboard-title">Chào Lan Anh</h1><p>Hôm nay, hãy chọn một mục tiêu nhỏ và tiến gần hơn đến điểm IELTS bạn mong muốn.</p><div class="student-dashboard-hero-actions">${link('student-class-detail.html?tab=assignments','Làm bài tập','white','book')}${link('student-class-detail.html?tab=schedule','Xem lịch trình','ghost','calendar')}</div></div><aside class="student-dashboard-progress" aria-label="Gợi ý tiến độ hôm nay"><span class="student-dashboard-progress-icon">${icon('chart')}</span><div><p>TIẾN ĐỘ HÔM NAY</p><strong>1 bước nhỏ</strong><span>Chọn một bài tập để bắt đầu.</span></div></aside></section><div class="student-dashboard-stats">${stat('Bài cần hoàn thành','—','Sẵn sàng để bạn chinh phục','book','blue','data-count="pending"')}${stat('Bài đã nộp','—','Đang được lưu trong hành trình','file','violet','data-count="submissions"')}${stat('Kết quả đã có','—','Phản hồi mới từ giáo viên','check','green','data-count="published"')}</div><div class="student-dashboard-grid"><section>${panel('Bài tập cần làm',taskList('assignment-list','student-dashboard-assignment-list'),link('student-class-detail.html?tab=assignments','Xem tất cả','text','arrow'),'student-assignment-panel')}</section><aside class="student-dashboard-side">${panel('Lịch trình hôm nay',scheduleList,link('student-class-detail.html?tab=schedule','Xem lịch trình','text','calendar'),'student-schedule-panel')}</aside></div>`;
function dashboard(role){return role==='student'?studentDashboard():teacherDashboard();}
add('teacher-dashboard.html','Tổng quan',dashboard('teacher'),'teacher');
add('student-dashboard.html','Tổng quan',dashboard('student'),'student');

function classWorkspace(role, overview) {
 const teacher=role==='teacher';
 const items=teacher?[['assignments','Bài tập'],['documents','Tài liệu'],['students','Học sinh'],['schedule','Lịch trình'],['settings','Cài đặt lớp']]:[['assignments','Bài tập'],['documents','Tài liệu'],['schedule','Lịch trình'],['results','Kết quả']];
 const tabNav='<nav class="tabs class-tabs" role="tablist" aria-label="Nội dung lớp học">'+items.map(([key,label],index)=>`<a id="class-tab-${key}" href="${role}-class-detail.html?tab=${key}" data-class-tab="${key}" role="tab" aria-selected="${index===0}" aria-controls="class-panel-${key}" tabindex="${index===0?'0':'-1'}" class="${index===0?'active':''}">${label}</a>`).join('')+'</nav>';
 const assignments=teacher?`${panel('Bài tập đang diễn ra',taskList('class-assignments-list'),link('teacher-assignment-new.html','Tạo bài tập','primary','plus'),'class-assignment-panel')}${panel('Bài tập đã hoàn thành',taskList('class-completed-assignments-list'),'','class-assignment-panel class-completed-assignment-panel')}`:panel('Bài tập chờ làm',taskList('class-assignments-list'),'','class-assignment-panel');
 const students=teacher?panel('Học sinh trong lớp',classStudentTable()):'';
 const documents=teacher?panel('Tài liệu của lớp','<div class="class-document-list" data-class-documents-list></div>',button('Tải tài liệu lên','open-class-document-upload','primary','plus'),'class-documents-panel'):panel('Tài liệu của lớp','<div class="class-document-list student-class-document-list" data-student-class-documents-list></div>','','class-documents-panel');
 const settings=teacher?`${panel('Cài đặt lớp',`<form data-form="class-settings">${input('Tên lớp','name','text','Tên lớp','required maxlength="100"')}${area('Mô tả','description','Giới thiệu mục tiêu và nội dung của lớp','maxlength="500"')}${input('Mật khẩu lớp','classPassword','password','Để trống nếu lớp không có mật khẩu')}<div class="form-actions">${saveButton('Lưu thay đổi')}</div></form>`)}${panel('Xóa lớp','<p>Xóa vĩnh viễn lớp học cùng các bài tập và bài nộp liên quan.</p><button class="btn danger" type="button" data-action="delete-class">Xóa lớp</button>','','class-danger-zone')}`:'';
 const contents={overview,assignments,documents,students,schedule:panel('Lịch trình của lớp',calendar(role)),settings,results:panel('Kết quả của lớp','<div id="student-class-results-list"></div>')};
 return tabNav+'<div class="class-tab-panels">'+items.map(([key],index)=>`<div id="class-panel-${key}" role="tabpanel" aria-labelledby="class-tab-${key}" data-class-panel="${key}" ${index===0?'':'hidden'}>${contents[key]}</div>`).join('')+'</div>';
}

for(const role of ['teacher','student']){
 const own=role==='student';
 add(`${role}-classes.html`,own?'Lớp của tôi':'Quản lý lớp học',role==='teacher'?teacherClassDirectory():own?studentClassDirectory():pageHead('Lớp học','Tổ chức lớp, kết nối học sinh và quản lý hoạt động học tập.',link(`${role}-class-new.html`,'Tạo lớp mới','primary','plus'))+filter('Tìm theo tên hoặc mã lớp')+`<div id="class-list" class="class-grid"></div>`,role,`${role}-classes.html`);
 const classMeta=own?`<div class="class-meta"><span>${icon('users')}Nhóm học sinh mẫu</span><span>${icon('calendar')}Thứ 2 · 4 · 6</span><span>${icon('clock')}18:30 – 20:00</span></div>`:`<div class="class-meta"><span>${icon('users')}Số lượng học sinh: <strong data-class-student-count>0</strong> học sinh</span></div>`;
 const overview=own?'':`<div class="dashboard-columns"><div>${panel('Bài tập đang diễn ra',taskList('class-overview-assignments-list'),'','class-assignment-panel')}${panel('Bài tập đã hoàn thành',taskList('class-overview-completed-assignments-list'),'','class-assignment-panel class-completed-assignment-panel')}${panel('Học sinh trong lớp',classStudentTable())}</div><aside>${panel('Thông tin tham gia lớp',`<dl class="detail-list class-access-details"><div><dt>Mã lớp</dt><dd data-class-code>Đang tạo mã lớp…</dd></div><div><dt>Mật khẩu lớp</dt><dd data-class-password>Chưa đặt</dd></div><div><dt>Đường link tham gia</dt><dd><a data-class-join-link href="student-classes.html?join=1&amp;class=class-foundation">student-classes.html?join=1&amp;class=class-foundation</a></dd></div></dl>${button('Sao chép thông tin','copy-class-access','outline','file')}`)}${panel('Lịch sắp tới',scheduleList)}</aside></div>`;
 const teacherClassHero=`<section class="class-cover teacher-class-detail-hero" aria-labelledby="class-detail-title"><div class="teacher-class-detail-copy"><p class="teacher-class-detail-kicker">${icon('book')} KHÔNG GIAN LỚP HỌC</p><h1 id="class-detail-title" data-class-name>IELTS Foundation</h1><p data-class-description>Học đều đặn. Nắm kiến thức nền. Tự tin tiến bộ.</p><div class="class-meta">${icon('users')}<span>Số học sinh <strong data-class-student-count>0</strong></span>${icon('file')}<span><strong data-class-assignment-count>0</strong> bài đã giao</span></div></div><aside class="teacher-class-detail-summary"><div class="teacher-class-code-card"><span>MÃ LỚP</span><strong data-class-code>Đang tạo…</strong><small data-class-password-summary hidden></small></div>${link('teacher-assignment-new.html','Tạo bài tập','white','plus')}</aside></section>`;
 const studentClassHero=`<section class="student-class-detail-hero" aria-labelledby="class-detail-title"><div class="student-class-detail-copy"><p class="student-class-detail-kicker">${icon('book')} KHÔNG GIAN HỌC TẬP</p><h1 id="class-detail-title" data-class-name>IELTS Foundation</h1><p data-class-description>Không gian luyện tập cho hành trình IELTS đầu tiên.</p></div><aside class="student-class-detail-summary"><span>${icon('file')} BÀI TẬP CỦA LỚP</span><strong data-class-assignment-count>0</strong><small>bài tập đã được giao</small></aside></section>`;
 let classContent=(role==='teacher'?teacherClassHero:studentClassHero)+classWorkspace(role,overview);
 add(`${role}-class-detail.html`,'Chi tiết lớp',classContent,role,`${role}-classes.html`);
 if(!own)add(`${role}-class-new.html`,'Tạo lớp học',pageHead('Một lớp học mới, một khởi đầu mới.','Điền thông tin cơ bản để chuẩn bị không gian học tập.')+`<div class="form-layout form-layout-single">${panel('Thông tin lớp',`<form data-form="class">${input('Tên lớp','name','text','Ví dụ IELTS Foundation 01','required maxlength="100"')}${area('Mô tả','description','Giới thiệu mục tiêu và nội dung của lớp','maxlength="500"')}<div class="form-grid">${select('Trình độ','level',['Foundation','Intermediate','Advanced'])}${select('Hình thức','format',['Trực tuyến','Trực tiếp','Kết hợp'])}</div>${input('Mật khẩu lớp','classPassword','password','Nhập mật khẩu lớp')}<div class="form-actions">${link(`${role}-classes.html`,'Hủy','outline','')}${saveButton('Tạo lớp học')}</div></form>`)}</div>`,role,`${role}-classes.html`);
}

const assignmentDetails=`${input('Tên bài tập','assignmentTitle','text','Ví dụ: Bài kiểm tra giữa kỳ','maxlength="150"')}<label class="field deadline-field">Hạn cuối nộp bài<input name="deadline" type="datetime-local" required data-open-picker></label><div class="assignment-primary-class"><span>Lớp nhận bài</span><strong data-primary-class-name>Đang xác định lớp học…</strong><input type="hidden" name="classId" data-primary-class-id></div><fieldset class="field assignment-extra-classes"><legend>Giao cùng bài này cho lớp khác</legend><details class="class-multiselect" data-class-multiselect><summary><span data-extra-classes-label>Chọn thêm lớp học</span></summary><div class="class-multiselect-menu" data-extra-class-options><p class="caption">Đang tải danh sách lớp…</p></div></details></fieldset>`;
const assignmentContent=`<div class="assignment-sections" data-assignment-sections></div><button class="btn outline add-assignment-section" type="button" data-action="add-assignment-section">+ Thêm section</button>`;
add('teacher-assignment-new.html','Tạo bài tập',pageHead('Thiết kế một bài tập mới','Chia nội dung thành các section, tạo câu hỏi và giao cho lớp học phù hợp.')+`<form data-form="assignment" class="builder"><section>${panel('Nội dung bài tập',assignmentContent)}<div class="form-actions">${button('Lưu nháp','save-assignment-draft','outline')}${button('Xem trước','preview-assignment','outline','eye')}${saveButton('Giao bài')}</div></section><aside class="builder-aside">${panel('Thông tin bài tập',assignmentDetails,'','assignment-info-panel')}</aside></form>`,'teacher','teacher-classes.html');
add('teacher-assignment-preview.html','Xem trước bài tập',`<section class="teacher-assignment-preview-hero" aria-labelledby="assignment-preview-title"><div class="teacher-assignment-preview-copy"><p class="teacher-assignment-preview-kicker">${icon('eye')} XEM TRƯỚC BÀI TẬP</p><h1 id="assignment-preview-title" data-assignment-preview-title>Đang tải bài tập…</h1><p data-assignment-preview-deadline>Đang tải hạn nộp…</p></div><aside class="teacher-assignment-preview-summary" aria-label="Tóm tắt bài tập"><div class="teacher-assignment-preview-audience"><span>LỚP NHẬN BÀI</span><strong data-assignment-preview-class-name>Đang xác định…</strong></div><div class="teacher-assignment-preview-stats"><div><span>SECTION</span><strong data-assignment-preview-section-count>—</strong></div><div><span>CÂU HỎI</span><strong data-assignment-preview-question-count>—</strong></div></div><a class="btn white" data-assignment-results-link hidden href="teacher-assignment-results.html">Xem kết quả</a></aside></section><div id="assignment-preview"><p>Đang tải nội dung bài tập…</p></div>`,'teacher','teacher-classes.html');
add('teacher-assignment-results.html','Kết quả bài tập',`<div id="assignment-results"><p>Đang tải kết quả bài tập…</p></div>`,'teacher','teacher-classes.html');
add('teacher-submissions.html','Bài tập chờ nhận xét',`<section class="teacher-review-hero" aria-labelledby="teacher-review-title"><div><p class="teacher-review-kicker">${icon('file')} KHÔNG GIAN PHẢN HỒI</p><h1 id="teacher-review-title">Bài tập chờ nhận xét</h1><div class="teacher-review-hero-actions">${link('teacher-classes.html','Xem lớp học','white','book')}</div></div><div class="teacher-review-hero-count"><span>ĐANG CHỜ BẠN</span><strong data-count="review">—</strong><small>bài tập cần xử lý</small></div></section><div class="teacher-review-stats">${stat('Tổng bài nộp','—','Trong dữ liệu lớp học','file','blue','data-count="submissions"')}${stat('Chờ nhận xét','—','Cần giáo viên kiểm tra','clock','amber','data-count="review"')}${stat('Đã công bố','—','Học sinh đã có thể xem','check','green','data-count="published"')}</div><div class="teacher-review-workspace"><section class="teacher-review-list-panel"><div class="teacher-review-list-head"><div><p>DANH SÁCH BÀI NỘP</p><h2>Những bài cần xem</h2></div>${searchOnly('Tìm theo tên bài tập')}</div><div id="submission-list" class="teacher-review-list"></div></section><aside class="teacher-review-guide"><span class="teacher-review-guide-icon">${icon('check')}</span><p>QUY TRÌNH PHẢN HỒI</p><h2>Ba bước để hoàn tất</h2><ol><li><strong>Mở bài làm</strong><span>Kiểm tra câu trả lời và điểm tự động.</span></li><li><strong>Thêm nhận xét</strong><span>Ghi chú ngắn gọn để học sinh biết bước tiếp theo.</span></li><li><strong>Công bố kết quả</strong><span>Học sinh chỉ xem được sau khi bạn duyệt.</span></li></ol></aside></div>`,'teacher');
add('teacher-review.html','Duyệt bài làm',`<div id="review-content"></div>`,'teacher','teacher-submissions.html');
add('teacher-student-detail.html','Hồ sơ học sinh',pageHead('Hồ sơ học sinh','Thông tin và tiến bộ trong từng kỹ năng.')+`<div class="profile-hero">${person('LA','Nguyễn Lan Anh','lananh@example.test')}${badge('Đang học','green')}<span>IELTS Foundation</span></div><div class="dashboard-columns"><div>${panel('Kỹ năng học tập',bars())}${panel('Hoạt động gần đây',table(['Hoạt động','Kỹ năng','Ghi chú'],[['Bài Reading mẫu','Reading','Ví dụ hiển thị tiến độ'],['Luyện viết Task 2','Writing','Chưa có điểm thật'],['Luyện nói Part 2','Speaking','Chưa có điểm thật']]))}</div><aside>${panel('Thông tin liên hệ',`<dl class="detail-list"><div><dt>Email học sinh</dt><dd>lananh@example.test</dd></div><div><dt>Phụ huynh</dt><dd>Chưa bổ sung</dd></div><div><dt>Email phụ huynh</dt><dd>Không bắt buộc</dd></div></dl>${button('Xem trước thông báo','email-preview','outline','bell')}`)}</aside></div>`,'teacher','teacher-classes.html');
add('teacher-reports.html','Báo cáo học tập',pageHead('Nhìn thấy tiến bộ của lớp.','So sánh kỹ năng và nhận ra nơi học sinh cần thêm hỗ trợ.')+`<div class="notice">Báo cáo minh họa bố cục, chưa tổng hợp dữ liệu thật.</div><div class="two-col">${panel('Phân bố theo kỹ năng',bars())}${panel('Mức độ hoàn thành minh họa',`<div class="donut" role="img" aria-label="75 phần trăm minh họa"><div><strong>75%</strong><span>Hoàn thành</span></div></div><div class="legend"><span class="dot"></span>Đã hoàn thành <span class="dot pale"></span>Còn lại</div>${demo}`)}</div>`+panel('Học sinh cần quan tâm',table(['Học sinh','Ghi chú',''],[[person('LA','Nguyễn Lan Anh'),'Cần thêm bài luyện viết',link('teacher-student-detail.html','Xem hồ sơ','text')],[person('MH','Trần Minh Hải'),'Cần luyện phản xạ nói',link('teacher-student-detail.html','Xem hồ sơ','text')]])),'teacher');

add('student-assignment-detail.html','Chi tiết bài tập',pageHead('Chuẩn bị cho bài luyện tập','Đọc kỹ hướng dẫn trước khi bắt đầu.')+`<div id="assignment-detail"></div>`,'student','student-classes.html');
add('student-reading.html','Làm bài tập',pageHead('Bài tập của bạn','Đọc kỹ đề bài và hoàn thành trước hạn nộp.')+`<div id="reading-workspace"></div>`,'student','student-classes.html');
add('student-listening.html','Làm bài Listening',pageHead('Listen with purpose.','Giao diện luyện nghe · Chưa có đề nghe hoặc dịch vụ chấm thật.')+`<div class="exam-layout">${panel('Audio bài nghe',`<div class="audio-cover">${icon('audio')}<h2>Listening practice</h2><p>Chọn một file audio trên máy để thử trình phát.</p></div><label class="upload-zone">Chọn audio xem thử<input type="file" accept="audio/*" data-audio-preview></label><audio id="audio-preview" controls hidden></audio><p class="caption">Audio được phát cục bộ, không tải lên server.</p>${area('Ghi chú khi nghe','listeningNotes','Ghi lại các từ khóa...','data-draft="listening-notes"')}`)}${panel('Câu trả lời',`<form data-form="sample-exam">${input('1. What is the name of the course?','a1','text','Câu trả lời của bạn')}${input('2. When does the course begin?','a2','text','Câu trả lời của bạn')}${input('3. How long does the lesson last?','a3','text','Câu trả lời của bạn')}<div class="notice">Câu hỏi minh họa không đi kèm đáp án để chấm.</div>${saveButton('Kiểm tra giao diện nộp bài')}</form>`)}</div>`,'student','student-classes.html');
add('student-writing.html','Làm bài Writing',pageHead('Make your ideas heard.','Writing Task 2 · Luyện diễn đạt ý tưởng bằng tiếng Anh.')+`<div class="exam-layout">${panel('Đề bài minh họa',`<span class="badge violet">Task 2</span><h2 class="prompt">Some people believe that technology makes education more accessible. To what extent do you agree or disagree?</h2><p>Give reasons for your answer and include any relevant examples from your own knowledge or experience.</p><div class="detail-list"><div><dt>Mục tiêu</dt><dd>250 từ</dd></div><div><dt>Thời gian gợi ý</dt><dd>40 phút</dd></div></div><div class="info-card"><h3>Trước khi viết</h3><p>Xác định quan điểm, lập dàn ý và chọn ví dụ phù hợp.</p></div>`)}${panel('Bài viết của bạn',`<form data-form="sample-exam">${area('Nội dung bài viết','essay','Start writing here...','class="writing-area" data-draft="writing-task2" data-word-count maxlength="20000"')}<div class="editor-footer"><span id="word-count">0 từ</span><span data-autosave-status>Lưu nháp trên trình duyệt</span></div><div class="form-actions">${button('Lưu bản nháp','save-writing','outline')}${saveButton('Xem trước nộp bài')}</div><p class="caption">Chưa gửi bài tới AI hoặc tạo điểm thật.</p></form>`)}</div>`,'student','student-classes.html');
add('student-speaking.html','Làm bài Speaking',pageHead('Your voice, your story.','Speaking Part 2 · Tự tin diễn đạt suy nghĩ của bạn.')+`<div class="exam-layout">${panel('Cue card minh họa',`<span class="badge amber">Part 2</span><h2 class="prompt">Describe a place you like to visit in your free time.</h2><p>You should say:</p><ul class="bullet-list"><li>Where it is</li><li>How often you go there</li><li>What you do there</li><li>And explain why you enjoy visiting this place</li></ul><div class="detail-list"><div><dt>Chuẩn bị</dt><dd>1 phút</dd></div><div><dt>Thời gian nói gợi ý</dt><dd>1–2 phút</dd></div></div>`)}${panel('Bản ghi âm của bạn',`<div class="recording-demo"><span class="microphone">${icon('mic')}</span><strong>00:00</strong><p>Thử giao diện bằng một file ghi âm có sẵn.</p><label class="btn primary upload-btn">${icon('audio')}Chọn file ghi âm<input type="file" accept="audio/*" data-audio-preview></label></div><audio id="audio-preview" controls hidden></audio><p class="caption">Chưa thu âm trực tiếp, chưa phân tích giọng nói. File chỉ phát trên máy, không tải lên.</p>${area('Ghi chú luyện nói','speakingNotes','Ý chính hoặc từ vựng cần dùng...','data-draft="speaking-notes"')}`)}</div>`,'student','student-classes.html');
add('student-submissions.html','Bài đã nộp',pageHead('Nhìn lại những gì bạn đã hoàn thành.','Bài làm và trạng thái chấm điểm của bạn.')+panel('Lịch sử bài nộp','<div id="student-submission-list"></div>'),'student');
add('student-result-detail.html','Chi tiết kết quả',pageHead('Phản hồi cho bài làm của bạn','Xem câu trả lời và những điều bạn đã làm được.')+'<div id="result-detail"></div>','student','student-classes.html');
add('student-profile.html','Hồ sơ học tập',`<section class="student-profile-page" aria-labelledby="student-profile-title"><header class="student-profile-page-head"><p>HỒ SƠ HỌC TẬP</p><h1 id="student-profile-title">Hành trình của riêng bạn</h1><span>Cập nhật thông tin và theo dõi bức tranh kỹ năng học tập của bạn.</span></header><form data-form="profile" class="student-profile-form"><section class="student-profile-hero"><label class="student-avatar-picker" title="Thay ảnh đại diện"><span class="student-profile-avatar" data-student-avatar>LA</span><span class="student-avatar-edit" aria-hidden="true">${icon('pen')}</span><input type="file" accept="image/png,image/jpeg,image/webp" data-student-avatar-file aria-label="Tải ảnh đại diện"></label><div><p>HỌC SINH</p><h2 data-student-name>Nguyễn Lan Anh</h2></div></section><p class="student-avatar-caption" data-student-avatar-file-name>Nhấn vào ảnh đại diện để tải ảnh PNG, JPG hoặc WebP (tối đa 1 MB).</p><div class="student-profile-grid"><section class="student-profile-card"><div class="student-profile-card-heading">${icon('users')}<div><h2>Thông tin cá nhân</h2><p>Thông tin giúp giáo viên nhận diện và đồng hành cùng bạn.</p></div></div>${input('Họ và tên','name','text','Tên hiển thị','value="Nguyễn Lan Anh" required maxlength="100"')}${input('Email','email','email','Email liên hệ','value="lananh@example.test" required')}${input('Số điện thoại','phone','tel','Không bắt buộc')}<h3 class="student-profile-section-title">Thông tin phụ huynh</h3>${input('Tên phụ huynh','parentName','text','Không bắt buộc')}${input('Số điện thoại phụ huynh','parentPhone','tel','Không bắt buộc')}${input('Email phụ huynh','parentEmail','email','Không bắt buộc')}</section><aside class="student-profile-side"><section class="student-profile-card student-profile-progress"><div class="student-profile-card-heading">${icon('chart')}<div><h2>Đánh giá kĩ năng</h2><p>Dựa trên các bài làm đã được chấm.</p></div></div><div data-student-skill-analysis></div></section></aside></div><section class="student-profile-password"><span class="student-profile-password-icon">${icon('shield')}</span><div><h2>Đổi mật khẩu</h2><p>Cập nhật mật khẩu để bảo vệ tài khoản học tập của bạn.</p>${link('reset-password.html','Đổi mật khẩu','outline')}</div></section><footer class="student-profile-save">${saveButton('Lưu thay đổi')}</footer></form></section>`,'student');

const adminPanel=(route,content)=>`<section class="admin-spa-panel" data-admin-panel="${route}" ${route==='overview'?'':'hidden'}>${content}</section>`;
const adminOverview=`<section class="admin-dashboard-hero" aria-labelledby="admin-dashboard-title"><div class="admin-dashboard-hero-copy"><p>QUẢN TRỊ HỆ THỐNG</p><h1 id="admin-dashboard-title">Tổng quan hệ thống</h1><span>Theo dõi quy mô không gian học tập.</span></div><div class="admin-dashboard-hero-summary" aria-label="Tóm tắt hệ thống"><div><span>Tài khoản</span><strong>${String(people.length + 1).padStart(2,'0')}</strong><small>Học sinh và giáo viên</small></div><div><span>Lớp học</span><strong data-count="classes">—</strong><small>Đang hoạt động</small></div></div></section><div class="dashboard-columns admin-dashboard-grid"><div>${panel('Người dùng mẫu',table(['Người dùng','Vai trò','Trạng thái',''],studentRows(true)),link('admin.html#users','Xem tất cả','text'))}</div><aside>${panel('Thiết lập hệ thống',`<div class="quick-links">${link('admin.html#prompt','Cấu hình dịch vụ AI','outline','shield')}${link('admin.html#settings','Cài đặt AI','outline','settings')}${link('admin.html#quota','Thiết lập hạn mức','outline','chart')}${link('admin.html#audit','Xem nhật ký','outline','file')}</div>`)}</aside></div>`;
const adminUsers=pageHead('Quản lý tài khoản','Tra cứu người dùng và xem thông tin theo vai trò.',button('Thêm người dùng','add-user','primary','plus'))+panel('Người dùng minh họa',filter('Tìm tên hoặc email',['Tất cả','Học sinh','Giáo viên'])+table(['Người dùng','Vai trò','Hành động'],adminUserRows(),'class="admin-users-table" data-filter-table'));
const adminUserDetail=pageHead('Thông tin người dùng','Trang quản lý tài khoản dành riêng cho quản trị viên.',link('admin.html#users','Về danh sách','outline',''))+`<div class="profile-hero">${person('LA','Nguyễn Lan Anh','lananh@example.test')}${badge('Học sinh')}</div><div class="two-col">${panel('Thông tin tài khoản',`<form data-form="admin-user">${input('Họ và tên','name','text','','value="Nguyễn Lan Anh" required')}${input('Email','email','email','','value="lananh@example.test" required')}${select('Vai trò','userRole',['Học sinh','Giáo viên'])}${select('Trạng thái tài khoản','status',['Hoạt động','Tạm khóa'])}${saveButton('Xem trước thay đổi')}<p class="caption">Không thay đổi tài khoản thật. Quyền admin chỉ được cấp bởi hệ thống phía server.</p></form>`)}${panel('Lớp và hoạt động',`<div class="class-card static"><span class="class-letter">F</span><h3>IELTS Foundation</h3><p>Học sinh · Lớp minh họa</p></div>${button('Xem trước khóa tài khoản','lock-user','danger')}`)}</div>`;
const promptName=index=>`<label class="prompt-row-name"><span class="sr-only">Tên prompt</span><input name="promptName${index}" data-prompt-name value="Prompt ${index+1}" maxlength="120" aria-label="Tên prompt"></label>`;
const writingPromptRow=index=>`<details class="prompt-row" data-prompt-row><summary>${promptName(index)}<button class="class-student-action delete" type="button" data-action="remove-prompt-row" aria-label="Xóa prompt ${index+1}" title="Xóa prompt">${icon('trash')}</button></summary><div class="prompt-row-content"><div class="prompt-row-controls">${select('Part',`writingPart${index}`,[['task1','Part 1'],['task2','Part 2']],'data-writing-prompt-part')}${select('Dạng',`writingType${index}`,['Line Graph','Bar Graph','Pie Graph','Table','Map','Process','Mixed Chart'],'data-writing-prompt-type')}</div><div class="prompt-row-fields">${area('Prompt TA',`writingTa${index}`,'Nhập prompt Task Achievement...','maxlength="10000"')}${area('Prompt LR',`writingLr${index}`,'Nhập prompt Lexical Resource...','maxlength="10000"')}${area('Prompt GRA',`writingGra${index}`,'Nhập prompt Grammar Range & Accuracy...','maxlength="10000"')}</div></div></details>`;
const speakingPromptRow=index=>`<details class="prompt-row prompt-row-speaking" data-prompt-row><summary>${promptName(index)}<button class="class-student-action delete" type="button" data-action="remove-prompt-row" aria-label="Xóa prompt ${index+1}" title="Xóa prompt">${icon('trash')}</button></summary><div class="prompt-row-content"><div class="prompt-row-controls">${select('Speaking task',`speakingTask${index}`,['Speaking Task 1','Speaking Task 2','Speaking Task 3'],'data-speaking-prompt-task')}</div><div class="prompt-row-fields">${area('Prompt GRLR',`speakingGrlr${index}`,'Nhập prompt Grammatical Range & Lexical Resource...','maxlength="10000"')}${area('Prompt FCPR',`speakingFcpr${index}`,'Nhập prompt Fluency, Coherence, Pronunciation & Relevance...','maxlength="10000"')}</div></div></details>`;
const promptSection=(title,description,iconName,kind,row)=>`<details class="prompt-collapse"><summary><span class="prompt-collapse-icon">${icon(iconName)}</span><span><strong>${title}</strong><small>${description}</small></span></summary><form data-form="${kind}" class="prompt-editor"><div class="prompt-list" data-prompt-list="${kind}">${row(0)}</div><div class="form-actions">${button('Thêm prompt',`add-${kind}`,'outline','plus')}${saveButton('Lưu prompt')}</div></form></details>`;
const adminPrompt=pageHead('Cài đặt prompt','Tạo prompt đánh giá riêng cho từng dạng bài viết và bài nói.')+`<section class="prompt-config">${promptSection('Chấm bài viết','Thiết lập tiêu chí cho từng Part và dạng Writing.','pen','writing-prompts',writingPromptRow)}${promptSection('Chấm nói','Thiết lập tiêu chí cho từng Speaking task.','mic','speaking-prompts',speakingPromptRow)}</section>`;
const quotaUsageChart=()=>{const writing=[3,5,4,7,6,8,5,9,7,6,10,8,11,7,9,12,10,8,13,11,9,14,12,10,15,13,11,16,14,12],speaking=[2,3,2,4,3,5,4,5,3,6,5,4,6,5,7,6,5,8,7,6,8,7,9,8,7,10,8,9,11,10],width=930,height=260,left=44,right=18,top=18,bottom=34,max=20,plotWidth=width-left-right,plotHeight=height-top-bottom,point=(value,index)=>`${(left+index*plotWidth/29).toFixed(1)},${(top+(max-value)*plotHeight/max).toFixed(1)}`,grid=[0,5,10,15,20].map(value=>{const y=(top+(max-value)*plotHeight/max).toFixed(1);return `<g><line x1="${left}" y1="${y}" x2="${width-right}" y2="${y}"/><text x="${left-10}" y="${Number(y)+4}" text-anchor="end">${value}</text></g>`}).join(''),days=Array.from({length:30},(_,index)=>`<text x="${(left+index*plotWidth/29).toFixed(1)}" y="${height-10}" text-anchor="middle">${index+1}</text>`).join('');return `<figure class="quota-chart" data-quota-chart><figcaption><div><h3>30 ngày trong tháng</h3><p>Lượt chấm theo ngày của giáo viên.</p></div><div class="quota-chart-legend"><span><i class="writing"></i>Writing</span><span><i class="speaking"></i>Speaking</span></div></figcaption><div class="quota-chart-scroll"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Biểu đồ lượt chấm Writing và Speaking trong 30 ngày"><g class="quota-chart-grid">${grid}</g><polyline class="quota-chart-line writing" points="${writing.map(point).join(' ')}"/><polyline class="quota-chart-line speaking" points="${speaking.map(point).join(' ')}"/><g class="quota-chart-days">${days}</g></svg></div><p class="caption">Dữ liệu minh họa của tháng hiện tại.</p></figure>`;};
const adminQuota=pageHead('Chủ động kiểm soát mức sử dụng.','Thiết lập quota chấm bài cho giáo viên và theo dõi mức dùng trong tháng.')+panel('Hạn mức giáo viên',`<form data-form="limits"><div class="form-grid">${input('Quota Writing mỗi ngày','writingDailyLimit','number','','value="20" required min="0" max="100000"')}${input('Quota Writing mỗi tháng','writingMonthlyLimit','number','','value="400" required min="0" max="100000"')}${input('Quota Speaking mỗi ngày','speakingDailyLimit','number','','value="20" required min="0" max="100000"')}${input('Quota Speaking mỗi tháng','speakingMonthlyLimit','number','','value="400" required min="0" max="100000"')}${input('Ngân sách tháng dự kiến bằng USD','budget','number','','value="25" required min="0" step="0.01"')}</div>${select('Khi đạt hạn mức','limitPolicy',['Tạm dừng và thông báo','Chờ quản trị viên duyệt'])}${saveButton('Lưu hạn mức')}</form>`)+panel('Theo dõi sử dụng',quotaUsageChart());
const adminAudit=pageHead('Theo dõi các thay đổi trong hệ thống.','Nhật ký mẫu ghi thao tác cục bộ, chưa thay thế audit log phía server.')+panel('Hoạt động gần đây','<div id="audit-list"></div>');
const adminSettings=pageHead('Thiết lập không gian học tập','Cấu hình các API phục vụ chấm bài.')+panel('Kết nối API',`<form data-form="ai-api-settings"><div class="form-grid">${input('API chấm Writing','writingGradingApi','url','https://api.example.com','autocomplete="off"')}${input('API nghe lời học sinh nói','speechListeningApi','url','https://api.example.com','autocomplete="off"')}${input('API chấm Listening','listeningGradingApi','url','https://api.example.com','autocomplete="off"')}</div>${saveButton('Lưu cài đặt')}</form>`);
add('admin.html','Tổng quan hệ thống',[['overview',adminOverview],['users',adminUsers],['user-detail',adminUserDetail],['prompt',adminPrompt],['quota',adminQuota],['settings',adminSettings],['audit',adminAudit]].map(([route,content])=>adminPanel(route,content)).join(''),'admin');
add('notifications.html','Thông báo',pageHead('Cập nhật từ lớp học của bạn','Bài tập, lịch học và kết quả được tập trung tại đây.',button('Đánh dấu đã đọc','read-all','outline','check'))+panel('Thông báo minh họa',`<div id="notification-list">${[['file','Chào mừng đến với English Assistant','Khám phá lớp học và bài tập đầu tiên của bạn.','student-dashboard.html'],['calendar','Đừng quên lịch học tuần này','Mở lịch để xem các buổi học minh họa.','student-class-detail.html?tab=schedule'],['check','Theo dõi kết quả học tập','Kết quả thật trong bản mẫu chỉ xuất hiện sau khi giáo viên công bố.','student-class-detail.html?tab=results']].map(([i,t,p,h])=>`<a class="notification-item" href="${h}"><span class="stat-icon blue">${icon(i)}</span><div><h3>${t}</h3><p>${p}</p><small>Thông báo minh họa</small></div><span class="unread-dot"></span></a>`).join('')}</div>`),'student','student-dashboard.html');
add('settings.html','Hồ sơ giáo viên',`<section class="teacher-profile-page" aria-labelledby="teacher-profile-title"><div class="teacher-profile-page-head"><p>THIẾT LẬP CÁ NHÂN</p><h1 id="teacher-profile-title">Hồ sơ giáo viên</h1><span>Quản lý thông tin hiển thị và thông báo của thầy/cô.</span></div><form class="teacher-profile-form" data-form="teacher-profile"><section class="teacher-profile-hero"><span class="teacher-profile-avatar" data-teacher-avatar>GV</span><div><p>HỒ SƠ GIẢNG DẠY</p><h2 data-teacher-name>Giáo viên mẫu</h2><span>Thông tin này sẽ hiển thị trong không gian lớp học.</span></div><label class="teacher-avatar-picker">${icon('pen')}<span>Thay ảnh đại diện</span><input type="file" accept="image/png,image/jpeg,image/webp" data-teacher-avatar-file aria-label="Tải ảnh đại diện"></label></section><p class="teacher-avatar-caption" data-teacher-avatar-file-name>Hỗ trợ PNG, JPG hoặc WebP, tối đa 1 MB.</p><div class="teacher-profile-grid"><section class="teacher-profile-card"><div class="teacher-profile-card-heading">${icon('users')}<div><h2>Thông tin cá nhân</h2><p>Thông tin cơ bản để học sinh nhận diện thầy/cô.</p></div></div>${input('Tên hiển thị','name','text','Tên hiển thị','value="Giáo viên mẫu" required maxlength="100" autocomplete="name"')}${input('Email liên hệ','email','email','teacher@example.test','value="teacher@example.test" required autocomplete="email"')}${area('Giới thiệu','bio','Giới thiệu ngắn về cách giảng dạy...','maxlength="500"')}</section><aside class="teacher-profile-card teacher-notifications-card"><div class="teacher-profile-card-heading">${icon('bell')}<div><h2>Thông báo</h2><p>Các tùy chọn cài đặt thông báo</p></div></div><label class="switch-row"><span><strong>Nhắc lịch học</strong><small>Thông báo trước khi buổi học bắt đầu.</small></span><input type="checkbox" name="reminder" checked></label><label class="switch-row"><span><strong>Bài tập mới</strong><small>Thông báo học sinh khi giao bài tập mới</small></span><input type="checkbox" name="submission" checked></label></aside></div><section class="teacher-profile-password"><div>${icon('shield')}<div><h2>Mật khẩu</h2><p>Đổi mật khẩu khi cần bảo mật tài khoản.</p></div></div>${link('reset-password.html','Đổi mật khẩu','outline','')}</section><div class="teacher-profile-save"><span>Mọi thay đổi được lưu trên trình duyệt này.</span>${saveButton('Lưu thay đổi')}</div></form></section>`,'teacher');
for(const code of ['403','404'])add(`${code}.html`,code==='403'?'Không có quyền truy cập':'Không tìm thấy trang',`<section class="container error-page"><span class="error-number">${code}</span><h1>${code==='403'?'Không gian này dành cho vai trò khác.':'Có vẻ bạn đã đi lạc một chút.'}</h1><p>${code==='403'?'Đăng nhập bằng tài khoản phù hợp để tiếp tục.':'Trang bạn tìm có thể đã đổi đường dẫn. Cùng quay lại điểm bắt đầu nhé.'}</p><div class="hero-actions">${link('login.html','Đăng nhập','outline','')}</div></section>`);
